### ISSUE TITLE
Attachments with name taking up 2 lines causes layout to look strange

### ISSUE THREAD

**Issue by fgoroncy** [AIESECGermany/myExperiencesOnline#18]
In the attachment tab when a attachment's name takes up two lines, the grids underneath are not displayed
![mein praktikum - my experiences online - google chrome_056](https://cloud.githubusercontent.com/assets/5617105/2689261/efa81e7c-c2f2-11e3-84ec-e979293d3bae.png)

**Comment by dwsoto** [comment]
functionality removed
