### ISSUE TITLE
Application Form for VEP Mentors

### ISSUE THREAD

**Issue by TimoSta** [AIESECGermany/myExperiencesOnline#25]
Application as Mentor for the Virtual Education Platform should be handled via My Experiences online.

To provide this functionality, we have to
* create an appropriate data representation in Salesforce,
* implement the form itself in Symfony using existing features like API-Connection and Authentication and
* Integrate the registration process in the VEP itself.

The detailed design is still to be done.

**Comment by dwsoto** [comment]
not using salesforce anymore
